#0
! **********************************
! Generated by: 
! Axes: XYZTR=XYZ
! Resolution: 1 counts per unit
! Source File: C:\Users\User\Desktop\Ji Zhang\Soft Matter paper\AuPPthic4\1-nafbot.dxf
! **********************************

! Make sure to update all Alignment positions before run
! Alignment Structure: 
If (gIntFindFids = 1)
     gDblFidX(1) = 0
     gDblFidY(1) = 0
     gDblFidX(2) = 0
     gDblFidY(2) = 0
     Stop
End

ptp/ev (X,Y),0.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),0.00000,0.50000
line (X,Y),0.00000,0.00000
line (X,Y),0.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),4.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),1.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),1.43636,3.70000
line (X,Y),1.43636,6.98182
arc2 (X,Y),1.45455,6.98182,-1.57080
arc2 (X,Y),1.45455,6.98182,-1.57080
line (X,Y),1.47273,3.71818
arc2 (X,Y),1.49091,3.71818,1.57080
arc2 (X,Y),1.49091,3.71818,1.57080
line (X,Y),1.50909,6.98182
arc2 (X,Y),1.52727,6.98182,-1.57080
arc2 (X,Y),1.52727,6.98182,-1.57080
line (X,Y),1.54546,3.71818
arc2 (X,Y),1.56364,3.71818,1.57080
arc2 (X,Y),1.56364,3.71818,1.57080
line (X,Y),1.58182,6.98182
arc2 (X,Y),1.60000,6.98182,-1.57080
arc2 (X,Y),1.60000,6.98182,-1.57080
line (X,Y),1.61818,3.71818
arc2 (X,Y),1.63636,3.71818,1.57080
arc2 (X,Y),1.63636,3.71818,1.57080
line (X,Y),1.65455,6.98182
arc2 (X,Y),1.67273,6.98182,-1.57080
arc2 (X,Y),1.67273,6.98182,-1.57080
line (X,Y),1.69091,3.71818
arc2 (X,Y),1.70909,3.71818,1.57080
arc2 (X,Y),1.70909,3.71818,1.57080
line (X,Y),1.72727,6.98182
arc2 (X,Y),1.74546,6.98182,-1.57080
arc2 (X,Y),1.74546,6.98182,-1.57080
line (X,Y),1.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),2.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),2.43636,1.00000
line (X,Y),2.43636,2.48182
arc2 (X,Y),2.45455,2.48182,-1.57080
arc2 (X,Y),2.45455,2.48182,-1.57080
line (X,Y),2.47273,1.01818
arc2 (X,Y),2.49091,1.01818,1.57080
arc2 (X,Y),2.49091,1.01818,1.57080
line (X,Y),2.50909,2.48182
arc2 (X,Y),2.52727,2.48182,-1.57080
arc2 (X,Y),2.52727,2.48182,-1.57080
line (X,Y),2.54546,1.01818
arc2 (X,Y),2.56364,1.01818,1.57080
arc2 (X,Y),2.56364,1.01818,1.57080
line (X,Y),2.58182,2.48182
arc2 (X,Y),2.60000,2.48182,-1.57080
arc2 (X,Y),2.60000,2.48182,-1.57080
line (X,Y),2.61818,1.01818
arc2 (X,Y),2.63636,1.01818,1.57080
arc2 (X,Y),2.63636,1.01818,1.57080
line (X,Y),2.65455,2.48182
arc2 (X,Y),2.67273,2.48182,-1.57080
arc2 (X,Y),2.67273,2.48182,-1.57080
line (X,Y),2.69091,1.01818
arc2 (X,Y),2.70909,1.01818,1.57080
arc2 (X,Y),2.70909,1.01818,1.57080
line (X,Y),2.72727,2.48182
arc2 (X,Y),2.74546,2.48182,-1.57080
arc2 (X,Y),2.74546,2.48182,-1.57080
line (X,Y),2.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),5.00000,0.50000
line (X,Y),5.00000,0.00000
line (X,Y),5.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),9.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),6.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),6.43636,3.70000
line (X,Y),6.43636,6.98182
arc2 (X,Y),6.45455,6.98182,-1.57080
arc2 (X,Y),6.45455,6.98182,-1.57080
line (X,Y),6.47273,3.71818
arc2 (X,Y),6.49091,3.71818,1.57080
arc2 (X,Y),6.49091,3.71818,1.57080
line (X,Y),6.50909,6.98182
arc2 (X,Y),6.52727,6.98182,-1.57080
arc2 (X,Y),6.52727,6.98182,-1.57080
line (X,Y),6.54546,3.71818
arc2 (X,Y),6.56364,3.71818,1.57080
arc2 (X,Y),6.56364,3.71818,1.57080
line (X,Y),6.58182,6.98182
arc2 (X,Y),6.60000,6.98182,-1.57080
arc2 (X,Y),6.60000,6.98182,-1.57080
line (X,Y),6.61818,3.71818
arc2 (X,Y),6.63636,3.71818,1.57080
arc2 (X,Y),6.63636,3.71818,1.57080
line (X,Y),6.65455,6.98182
arc2 (X,Y),6.67273,6.98182,-1.57080
arc2 (X,Y),6.67273,6.98182,-1.57080
line (X,Y),6.69091,3.71818
arc2 (X,Y),6.70909,3.71818,1.57080
arc2 (X,Y),6.70909,3.71818,1.57080
line (X,Y),6.72727,6.98182
arc2 (X,Y),6.74546,6.98182,-1.57080
arc2 (X,Y),6.74546,6.98182,-1.57080
line (X,Y),6.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),7.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),7.43636,1.00000
line (X,Y),7.43636,2.48182
arc2 (X,Y),7.45455,2.48182,-1.57080
arc2 (X,Y),7.45455,2.48182,-1.57080
line (X,Y),7.47273,1.01818
arc2 (X,Y),7.49091,1.01818,1.57080
arc2 (X,Y),7.49091,1.01818,1.57080
line (X,Y),7.50909,2.48182
arc2 (X,Y),7.52727,2.48182,-1.57080
arc2 (X,Y),7.52727,2.48182,-1.57080
line (X,Y),7.54546,1.01818
arc2 (X,Y),7.56364,1.01818,1.57080
arc2 (X,Y),7.56364,1.01818,1.57080
line (X,Y),7.58182,2.48182
arc2 (X,Y),7.60000,2.48182,-1.57080
arc2 (X,Y),7.60000,2.48182,-1.57080
line (X,Y),7.61818,1.01818
arc2 (X,Y),7.63636,1.01818,1.57080
arc2 (X,Y),7.63636,1.01818,1.57080
line (X,Y),7.65455,2.48182
arc2 (X,Y),7.67273,2.48182,-1.57080
arc2 (X,Y),7.67273,2.48182,-1.57080
line (X,Y),7.69091,1.01818
arc2 (X,Y),7.70909,1.01818,1.57080
arc2 (X,Y),7.70909,1.01818,1.57080
line (X,Y),7.72727,2.48182
arc2 (X,Y),7.74546,2.48182,-1.57080
arc2 (X,Y),7.74546,2.48182,-1.57080
line (X,Y),7.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),10.00000,0.50000
line (X,Y),10.00000,0.00000
line (X,Y),10.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),14.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),11.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),11.43636,3.70000
line (X,Y),11.43636,6.98182
arc2 (X,Y),11.45455,6.98182,-1.57080
arc2 (X,Y),11.45455,6.98182,-1.57080
line (X,Y),11.47273,3.71818
arc2 (X,Y),11.49091,3.71818,1.57080
arc2 (X,Y),11.49091,3.71818,1.57080
line (X,Y),11.50909,6.98182
arc2 (X,Y),11.52727,6.98182,-1.57080
arc2 (X,Y),11.52727,6.98182,-1.57080
line (X,Y),11.54545,3.71818
arc2 (X,Y),11.56364,3.71818,1.57080
arc2 (X,Y),11.56364,3.71818,1.57080
line (X,Y),11.58182,6.98182
arc2 (X,Y),11.60000,6.98182,-1.57080
arc2 (X,Y),11.60000,6.98182,-1.57080
line (X,Y),11.61818,3.71818
arc2 (X,Y),11.63636,3.71818,1.57080
arc2 (X,Y),11.63636,3.71818,1.57080
line (X,Y),11.65455,6.98182
arc2 (X,Y),11.67273,6.98182,-1.57080
arc2 (X,Y),11.67273,6.98182,-1.57080
line (X,Y),11.69091,3.71818
arc2 (X,Y),11.70909,3.71818,1.57080
arc2 (X,Y),11.70909,3.71818,1.57080
line (X,Y),11.72727,6.98182
arc2 (X,Y),11.74545,6.98182,-1.57080
arc2 (X,Y),11.74545,6.98182,-1.57080
line (X,Y),11.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),12.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),12.43636,1.00000
line (X,Y),12.43636,2.48182
arc2 (X,Y),12.45455,2.48182,-1.57080
arc2 (X,Y),12.45455,2.48182,-1.57080
line (X,Y),12.47273,1.01818
arc2 (X,Y),12.49091,1.01818,1.57080
arc2 (X,Y),12.49091,1.01818,1.57080
line (X,Y),12.50909,2.48182
arc2 (X,Y),12.52727,2.48182,-1.57080
arc2 (X,Y),12.52727,2.48182,-1.57080
line (X,Y),12.54545,1.01818
arc2 (X,Y),12.56364,1.01818,1.57080
arc2 (X,Y),12.56364,1.01818,1.57080
line (X,Y),12.58182,2.48182
arc2 (X,Y),12.60000,2.48182,-1.57080
arc2 (X,Y),12.60000,2.48182,-1.57080
line (X,Y),12.61818,1.01818
arc2 (X,Y),12.63636,1.01818,1.57080
arc2 (X,Y),12.63636,1.01818,1.57080
line (X,Y),12.65455,2.48182
arc2 (X,Y),12.67273,2.48182,-1.57080
arc2 (X,Y),12.67273,2.48182,-1.57080
line (X,Y),12.69091,1.01818
arc2 (X,Y),12.70909,1.01818,1.57080
arc2 (X,Y),12.70909,1.01818,1.57080
line (X,Y),12.72727,2.48182
arc2 (X,Y),12.74545,2.48182,-1.57080
arc2 (X,Y),12.74545,2.48182,-1.57080
line (X,Y),12.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),15.00000,0.50000
line (X,Y),15.00000,0.00000
line (X,Y),15.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),19.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),16.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),16.43636,3.70000
line (X,Y),16.43636,6.98182
arc2 (X,Y),16.45455,6.98182,-1.57080
arc2 (X,Y),16.45455,6.98182,-1.57080
line (X,Y),16.47273,3.71818
arc2 (X,Y),16.49091,3.71818,1.57080
arc2 (X,Y),16.49091,3.71818,1.57080
line (X,Y),16.50909,6.98182
arc2 (X,Y),16.52727,6.98182,-1.57080
arc2 (X,Y),16.52727,6.98182,-1.57080
line (X,Y),16.54545,3.71818
arc2 (X,Y),16.56364,3.71818,1.57080
arc2 (X,Y),16.56364,3.71818,1.57080
line (X,Y),16.58182,6.98182
arc2 (X,Y),16.60000,6.98182,-1.57080
arc2 (X,Y),16.60000,6.98182,-1.57080
line (X,Y),16.61818,3.71818
arc2 (X,Y),16.63636,3.71818,1.57080
arc2 (X,Y),16.63636,3.71818,1.57080
line (X,Y),16.65454,6.98182
arc2 (X,Y),16.67273,6.98182,-1.57080
arc2 (X,Y),16.67273,6.98182,-1.57080
line (X,Y),16.69091,3.71818
arc2 (X,Y),16.70909,3.71818,1.57080
arc2 (X,Y),16.70909,3.71818,1.57080
line (X,Y),16.72727,6.98182
arc2 (X,Y),16.74545,6.98182,-1.57080
arc2 (X,Y),16.74545,6.98182,-1.57080
line (X,Y),16.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),17.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),17.43636,1.00000
line (X,Y),17.43636,2.48182
arc2 (X,Y),17.45455,2.48182,-1.57080
arc2 (X,Y),17.45455,2.48182,-1.57080
line (X,Y),17.47273,1.01818
arc2 (X,Y),17.49091,1.01818,1.57080
arc2 (X,Y),17.49091,1.01818,1.57080
line (X,Y),17.50909,2.48182
arc2 (X,Y),17.52727,2.48182,-1.57080
arc2 (X,Y),17.52727,2.48182,-1.57080
line (X,Y),17.54545,1.01818
arc2 (X,Y),17.56364,1.01818,1.57080
arc2 (X,Y),17.56364,1.01818,1.57080
line (X,Y),17.58182,2.48182
arc2 (X,Y),17.60000,2.48182,-1.57080
arc2 (X,Y),17.60000,2.48182,-1.57080
line (X,Y),17.61818,1.01818
arc2 (X,Y),17.63636,1.01818,1.57080
arc2 (X,Y),17.63636,1.01818,1.57080
line (X,Y),17.65454,2.48182
arc2 (X,Y),17.67273,2.48182,-1.57080
arc2 (X,Y),17.67273,2.48182,-1.57080
line (X,Y),17.69091,1.01818
arc2 (X,Y),17.70909,1.01818,1.57080
arc2 (X,Y),17.70909,1.01818,1.57080
line (X,Y),17.72727,2.48182
arc2 (X,Y),17.74545,2.48182,-1.57080
arc2 (X,Y),17.74545,2.48182,-1.57080
line (X,Y),17.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),20.00000,0.50000
line (X,Y),20.00000,0.00000
line (X,Y),20.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),24.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),21.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),21.43636,3.70000
line (X,Y),21.43636,6.98182
arc2 (X,Y),21.45455,6.98182,-1.57080
arc2 (X,Y),21.45455,6.98182,-1.57080
line (X,Y),21.47273,3.71818
arc2 (X,Y),21.49091,3.71818,1.57080
arc2 (X,Y),21.49091,3.71818,1.57080
line (X,Y),21.50909,6.98182
arc2 (X,Y),21.52727,6.98182,-1.57080
arc2 (X,Y),21.52727,6.98182,-1.57080
line (X,Y),21.54545,3.71818
arc2 (X,Y),21.56364,3.71818,1.57080
arc2 (X,Y),21.56364,3.71818,1.57080
line (X,Y),21.58182,6.98182
arc2 (X,Y),21.60000,6.98182,-1.57080
arc2 (X,Y),21.60000,6.98182,-1.57080
line (X,Y),21.61818,3.71818
arc2 (X,Y),21.63636,3.71818,1.57080
arc2 (X,Y),21.63636,3.71818,1.57080
line (X,Y),21.65454,6.98182
arc2 (X,Y),21.67273,6.98182,-1.57080
arc2 (X,Y),21.67273,6.98182,-1.57080
line (X,Y),21.69091,3.71818
arc2 (X,Y),21.70909,3.71818,1.57080
arc2 (X,Y),21.70909,3.71818,1.57080
line (X,Y),21.72727,6.98182
arc2 (X,Y),21.74545,6.98182,-1.57080
arc2 (X,Y),21.74545,6.98182,-1.57080
line (X,Y),21.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),22.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),22.43636,1.00000
line (X,Y),22.43636,2.48182
arc2 (X,Y),22.45455,2.48182,-1.57080
arc2 (X,Y),22.45455,2.48182,-1.57080
line (X,Y),22.47273,1.01818
arc2 (X,Y),22.49091,1.01818,1.57080
arc2 (X,Y),22.49091,1.01818,1.57080
line (X,Y),22.50909,2.48182
arc2 (X,Y),22.52727,2.48182,-1.57080
arc2 (X,Y),22.52727,2.48182,-1.57080
line (X,Y),22.54545,1.01818
arc2 (X,Y),22.56364,1.01818,1.57080
arc2 (X,Y),22.56364,1.01818,1.57080
line (X,Y),22.58182,2.48182
arc2 (X,Y),22.60000,2.48182,-1.57080
arc2 (X,Y),22.60000,2.48182,-1.57080
line (X,Y),22.61818,1.01818
arc2 (X,Y),22.63636,1.01818,1.57080
arc2 (X,Y),22.63636,1.01818,1.57080
line (X,Y),22.65454,2.48182
arc2 (X,Y),22.67273,2.48182,-1.57080
arc2 (X,Y),22.67273,2.48182,-1.57080
line (X,Y),22.69091,1.01818
arc2 (X,Y),22.70909,1.01818,1.57080
arc2 (X,Y),22.70909,1.01818,1.57080
line (X,Y),22.72727,2.48182
arc2 (X,Y),22.74545,2.48182,-1.57080
arc2 (X,Y),22.74545,2.48182,-1.57080
line (X,Y),22.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),25.00000,0.50000
line (X,Y),25.00000,0.00000
line (X,Y),25.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),29.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),30.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),26.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),26.43636,3.70000
line (X,Y),26.43636,6.98182
arc2 (X,Y),26.45455,6.98182,-1.57080
arc2 (X,Y),26.45455,6.98182,-1.57080
line (X,Y),26.47273,3.71818
arc2 (X,Y),26.49091,3.71818,1.57080
arc2 (X,Y),26.49091,3.71818,1.57080
line (X,Y),26.50909,6.98182
arc2 (X,Y),26.52727,6.98182,-1.57080
arc2 (X,Y),26.52727,6.98182,-1.57080
line (X,Y),26.54545,3.71818
arc2 (X,Y),26.56364,3.71818,1.57080
arc2 (X,Y),26.56364,3.71818,1.57080
line (X,Y),26.58182,6.98182
arc2 (X,Y),26.60000,6.98182,-1.57080
arc2 (X,Y),26.60000,6.98182,-1.57080
line (X,Y),26.61818,3.71818
arc2 (X,Y),26.63636,3.71818,1.57080
arc2 (X,Y),26.63636,3.71818,1.57080
line (X,Y),26.65454,6.98182
arc2 (X,Y),26.67273,6.98182,-1.57080
arc2 (X,Y),26.67273,6.98182,-1.57080
line (X,Y),26.69091,3.71818
arc2 (X,Y),26.70909,3.71818,1.57080
arc2 (X,Y),26.70909,3.71818,1.57080
line (X,Y),26.72727,6.98182
arc2 (X,Y),26.74545,6.98182,-1.57080
arc2 (X,Y),26.74545,6.98182,-1.57080
line (X,Y),26.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),27.43636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),27.43636,1.00000
line (X,Y),27.43636,2.48182
arc2 (X,Y),27.45455,2.48182,-1.57080
arc2 (X,Y),27.45455,2.48182,-1.57080
line (X,Y),27.47273,1.01818
arc2 (X,Y),27.49091,1.01818,1.57080
arc2 (X,Y),27.49091,1.01818,1.57080
line (X,Y),27.50909,2.48182
arc2 (X,Y),27.52727,2.48182,-1.57080
arc2 (X,Y),27.52727,2.48182,-1.57080
line (X,Y),27.54545,1.01818
arc2 (X,Y),27.56364,1.01818,1.57080
arc2 (X,Y),27.56364,1.01818,1.57080
line (X,Y),27.58182,2.48182
arc2 (X,Y),27.60000,2.48182,-1.57080
arc2 (X,Y),27.60000,2.48182,-1.57080
line (X,Y),27.61818,1.01818
arc2 (X,Y),27.63636,1.01818,1.57080
arc2 (X,Y),27.63636,1.01818,1.57080
line (X,Y),27.65454,2.48182
arc2 (X,Y),27.67273,2.48182,-1.57080
arc2 (X,Y),27.67273,2.48182,-1.57080
line (X,Y),27.69091,1.01818
arc2 (X,Y),27.70909,1.01818,1.57080
arc2 (X,Y),27.70909,1.01818,1.57080
line (X,Y),27.72727,2.48182
arc2 (X,Y),27.74545,2.48182,-1.57080
arc2 (X,Y),27.74545,2.48182,-1.57080
line (X,Y),27.76364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

STOP
