#0
! **********************************
! Generated by: 
! Axes: XYZTR=XYZ
! Resolution: 1 counts per unit
! Source File: C:\Users\User\Desktop\Ji Zhang\Soft Matter paper\AuNafthic4\3-PPbot.dxf
! **********************************

! Make sure to update all Alignment positions before run
! Alignment Structure: 
If (gIntFindFids = 1)
     gDblFidX(1) = 0
     gDblFidY(1) = 0
     gDblFidX(2) = 0
     gDblFidY(2) = 0
     Stop
End

ptp/ev (X,Y),0.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),0.00000,0.50000
line (X,Y),0.00000,0.00000
line (X,Y),0.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),4.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),3.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),3.01818,1.00000
line (X,Y),3.01818,2.49091
arc2 (X,Y),3.02727,2.49091,-1.57080
arc2 (X,Y),3.02727,2.49091,-1.57080
line (X,Y),3.03636,1.00909
arc2 (X,Y),3.04546,1.00909,1.57080
arc2 (X,Y),3.04546,1.00909,1.57080
line (X,Y),3.05455,2.49091
arc2 (X,Y),3.06364,2.49091,-1.57080
arc2 (X,Y),3.06364,2.49091,-1.57080
line (X,Y),3.07273,1.00909
arc2 (X,Y),3.08182,1.00909,1.57080
arc2 (X,Y),3.08182,1.00909,1.57080
line (X,Y),3.09091,2.49091
arc2 (X,Y),3.10000,2.49091,-1.57080
arc2 (X,Y),3.10000,2.49091,-1.57080
line (X,Y),3.10909,1.00909
arc2 (X,Y),3.11818,1.00909,1.57080
arc2 (X,Y),3.11818,1.00909,1.57080
line (X,Y),3.12727,2.49091
arc2 (X,Y),3.13636,2.49091,-1.57080
arc2 (X,Y),3.13636,2.49091,-1.57080
line (X,Y),3.14546,1.00909
arc2 (X,Y),3.15455,1.00909,1.57080
arc2 (X,Y),3.15455,1.00909,1.57080
line (X,Y),3.16364,2.49091
arc2 (X,Y),3.17273,2.49091,-1.57080
arc2 (X,Y),3.17273,2.49091,-1.57080
line (X,Y),3.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),1.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),1.51818,3.80000
line (X,Y),1.51818,6.89091
arc2 (X,Y),1.52727,6.89091,-1.57080
arc2 (X,Y),1.52727,6.89091,-1.57080
line (X,Y),1.53636,3.80909
arc2 (X,Y),1.54546,3.80909,1.57080
arc2 (X,Y),1.54546,3.80909,1.57080
line (X,Y),1.55455,6.89091
arc2 (X,Y),1.56364,6.89091,-1.57080
arc2 (X,Y),1.56364,6.89091,-1.57080
line (X,Y),1.57273,3.80909
arc2 (X,Y),1.58182,3.80909,1.57080
arc2 (X,Y),1.58182,3.80909,1.57080
line (X,Y),1.59091,6.89091
arc2 (X,Y),1.60000,6.89091,-1.57080
arc2 (X,Y),1.60000,6.89091,-1.57080
line (X,Y),1.60909,3.80909
arc2 (X,Y),1.61818,3.80909,1.57080
arc2 (X,Y),1.61818,3.80909,1.57080
line (X,Y),1.62727,6.89091
arc2 (X,Y),1.63636,6.89091,-1.57080
arc2 (X,Y),1.63636,6.89091,-1.57080
line (X,Y),1.64546,3.80909
arc2 (X,Y),1.65455,3.80909,1.57080
arc2 (X,Y),1.65455,3.80909,1.57080
line (X,Y),1.66364,6.89091
arc2 (X,Y),1.67273,6.89091,-1.57080
arc2 (X,Y),1.67273,6.89091,-1.57080
line (X,Y),1.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),5.00000,0.50000
line (X,Y),5.00000,0.00000
line (X,Y),5.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),9.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),8.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),8.01818,1.00000
line (X,Y),8.01818,2.49091
arc2 (X,Y),8.02727,2.49091,-1.57080
arc2 (X,Y),8.02727,2.49091,-1.57080
line (X,Y),8.03636,1.00909
arc2 (X,Y),8.04546,1.00909,1.57080
arc2 (X,Y),8.04546,1.00909,1.57080
line (X,Y),8.05455,2.49091
arc2 (X,Y),8.06364,2.49091,-1.57080
arc2 (X,Y),8.06364,2.49091,-1.57080
line (X,Y),8.07273,1.00909
arc2 (X,Y),8.08182,1.00909,1.57080
arc2 (X,Y),8.08182,1.00909,1.57080
line (X,Y),8.09091,2.49091
arc2 (X,Y),8.10000,2.49091,-1.57080
arc2 (X,Y),8.10000,2.49091,-1.57080
line (X,Y),8.10909,1.00909
arc2 (X,Y),8.11818,1.00909,1.57080
arc2 (X,Y),8.11818,1.00909,1.57080
line (X,Y),8.12727,2.49091
arc2 (X,Y),8.13636,2.49091,-1.57080
arc2 (X,Y),8.13636,2.49091,-1.57080
line (X,Y),8.14545,1.00909
arc2 (X,Y),8.15455,1.00909,1.57080
arc2 (X,Y),8.15455,1.00909,1.57080
line (X,Y),8.16364,2.49091
arc2 (X,Y),8.17273,2.49091,-1.57080
arc2 (X,Y),8.17273,2.49091,-1.57080
line (X,Y),8.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),6.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),6.51818,3.80000
line (X,Y),6.51818,6.89091
arc2 (X,Y),6.52727,6.89091,-1.57080
arc2 (X,Y),6.52727,6.89091,-1.57080
line (X,Y),6.53636,3.80909
arc2 (X,Y),6.54546,3.80909,1.57080
arc2 (X,Y),6.54546,3.80909,1.57080
line (X,Y),6.55455,6.89091
arc2 (X,Y),6.56364,6.89091,-1.57080
arc2 (X,Y),6.56364,6.89091,-1.57080
line (X,Y),6.57273,3.80909
arc2 (X,Y),6.58182,3.80909,1.57080
arc2 (X,Y),6.58182,3.80909,1.57080
line (X,Y),6.59091,6.89091
arc2 (X,Y),6.60000,6.89091,-1.57080
arc2 (X,Y),6.60000,6.89091,-1.57080
line (X,Y),6.60909,3.80909
arc2 (X,Y),6.61818,3.80909,1.57080
arc2 (X,Y),6.61818,3.80909,1.57080
line (X,Y),6.62727,6.89091
arc2 (X,Y),6.63636,6.89091,-1.57080
arc2 (X,Y),6.63636,6.89091,-1.57080
line (X,Y),6.64545,3.80909
arc2 (X,Y),6.65455,3.80909,1.57080
arc2 (X,Y),6.65455,3.80909,1.57080
line (X,Y),6.66364,6.89091
arc2 (X,Y),6.67273,6.89091,-1.57080
arc2 (X,Y),6.67273,6.89091,-1.57080
line (X,Y),6.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),10.00000,0.50000
line (X,Y),10.00000,0.00000
line (X,Y),10.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),14.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),13.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),13.01818,1.00000
line (X,Y),13.01818,2.49091
arc2 (X,Y),13.02727,2.49091,-1.57080
arc2 (X,Y),13.02727,2.49091,-1.57080
line (X,Y),13.03636,1.00909
arc2 (X,Y),13.04545,1.00909,1.57080
arc2 (X,Y),13.04545,1.00909,1.57080
line (X,Y),13.05455,2.49091
arc2 (X,Y),13.06364,2.49091,-1.57080
arc2 (X,Y),13.06364,2.49091,-1.57080
line (X,Y),13.07273,1.00909
arc2 (X,Y),13.08182,1.00909,1.57080
arc2 (X,Y),13.08182,1.00909,1.57080
line (X,Y),13.09091,2.49091
arc2 (X,Y),13.10000,2.49091,-1.57080
arc2 (X,Y),13.10000,2.49091,-1.57080
line (X,Y),13.10909,1.00909
arc2 (X,Y),13.11818,1.00909,1.57080
arc2 (X,Y),13.11818,1.00909,1.57080
line (X,Y),13.12727,2.49091
arc2 (X,Y),13.13636,2.49091,-1.57080
arc2 (X,Y),13.13636,2.49091,-1.57080
line (X,Y),13.14545,1.00909
arc2 (X,Y),13.15455,1.00909,1.57080
arc2 (X,Y),13.15455,1.00909,1.57080
line (X,Y),13.16364,2.49091
arc2 (X,Y),13.17273,2.49091,-1.57080
arc2 (X,Y),13.17273,2.49091,-1.57080
line (X,Y),13.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),11.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),11.51818,3.80000
line (X,Y),11.51818,6.89091
arc2 (X,Y),11.52727,6.89091,-1.57080
arc2 (X,Y),11.52727,6.89091,-1.57080
line (X,Y),11.53636,3.80909
arc2 (X,Y),11.54545,3.80909,1.57080
arc2 (X,Y),11.54545,3.80909,1.57080
line (X,Y),11.55455,6.89091
arc2 (X,Y),11.56364,6.89091,-1.57080
arc2 (X,Y),11.56364,6.89091,-1.57080
line (X,Y),11.57273,3.80909
arc2 (X,Y),11.58182,3.80909,1.57080
arc2 (X,Y),11.58182,3.80909,1.57080
line (X,Y),11.59091,6.89091
arc2 (X,Y),11.60000,6.89091,-1.57080
arc2 (X,Y),11.60000,6.89091,-1.57080
line (X,Y),11.60909,3.80909
arc2 (X,Y),11.61818,3.80909,1.57080
arc2 (X,Y),11.61818,3.80909,1.57080
line (X,Y),11.62727,6.89091
arc2 (X,Y),11.63636,6.89091,-1.57080
arc2 (X,Y),11.63636,6.89091,-1.57080
line (X,Y),11.64545,3.80909
arc2 (X,Y),11.65455,3.80909,1.57080
arc2 (X,Y),11.65455,3.80909,1.57080
line (X,Y),11.66364,6.89091
arc2 (X,Y),11.67273,6.89091,-1.57080
arc2 (X,Y),11.67273,6.89091,-1.57080
line (X,Y),11.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),15.00000,0.50000
line (X,Y),15.00000,0.00000
line (X,Y),15.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),19.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),18.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),18.01818,1.00000
line (X,Y),18.01818,2.49091
arc2 (X,Y),18.02727,2.49091,-1.57080
arc2 (X,Y),18.02727,2.49091,-1.57080
line (X,Y),18.03636,1.00909
arc2 (X,Y),18.04545,1.00909,1.57080
arc2 (X,Y),18.04545,1.00909,1.57080
line (X,Y),18.05455,2.49091
arc2 (X,Y),18.06364,2.49091,-1.57080
arc2 (X,Y),18.06364,2.49091,-1.57080
line (X,Y),18.07273,1.00909
arc2 (X,Y),18.08182,1.00909,1.57080
arc2 (X,Y),18.08182,1.00909,1.57080
line (X,Y),18.09091,2.49091
arc2 (X,Y),18.10000,2.49091,-1.57080
arc2 (X,Y),18.10000,2.49091,-1.57080
line (X,Y),18.10909,1.00909
arc2 (X,Y),18.11818,1.00909,1.57080
arc2 (X,Y),18.11818,1.00909,1.57080
line (X,Y),18.12727,2.49091
arc2 (X,Y),18.13636,2.49091,-1.57080
arc2 (X,Y),18.13636,2.49091,-1.57080
line (X,Y),18.14545,1.00909
arc2 (X,Y),18.15454,1.00909,1.57080
arc2 (X,Y),18.15454,1.00909,1.57080
line (X,Y),18.16364,2.49091
arc2 (X,Y),18.17273,2.49091,-1.57080
arc2 (X,Y),18.17273,2.49091,-1.57080
line (X,Y),18.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),16.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),16.51818,3.80000
line (X,Y),16.51818,6.89091
arc2 (X,Y),16.52727,6.89091,-1.57080
arc2 (X,Y),16.52727,6.89091,-1.57080
line (X,Y),16.53636,3.80909
arc2 (X,Y),16.54545,3.80909,1.57080
arc2 (X,Y),16.54545,3.80909,1.57080
line (X,Y),16.55455,6.89091
arc2 (X,Y),16.56364,6.89091,-1.57080
arc2 (X,Y),16.56364,6.89091,-1.57080
line (X,Y),16.57273,3.80909
arc2 (X,Y),16.58182,3.80909,1.57080
arc2 (X,Y),16.58182,3.80909,1.57080
line (X,Y),16.59091,6.89091
arc2 (X,Y),16.60000,6.89091,-1.57080
arc2 (X,Y),16.60000,6.89091,-1.57080
line (X,Y),16.60909,3.80909
arc2 (X,Y),16.61818,3.80909,1.57080
arc2 (X,Y),16.61818,3.80909,1.57080
line (X,Y),16.62727,6.89091
arc2 (X,Y),16.63636,6.89091,-1.57080
arc2 (X,Y),16.63636,6.89091,-1.57080
line (X,Y),16.64545,3.80909
arc2 (X,Y),16.65454,3.80909,1.57080
arc2 (X,Y),16.65454,3.80909,1.57080
line (X,Y),16.66364,6.89091
arc2 (X,Y),16.67273,6.89091,-1.57080
arc2 (X,Y),16.67273,6.89091,-1.57080
line (X,Y),16.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),20.00000,0.50000
line (X,Y),20.00000,0.00000
line (X,Y),20.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),24.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),23.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),23.01818,1.00000
line (X,Y),23.01818,2.49091
arc2 (X,Y),23.02727,2.49091,-1.57080
arc2 (X,Y),23.02727,2.49091,-1.57080
line (X,Y),23.03636,1.00909
arc2 (X,Y),23.04545,1.00909,1.57080
arc2 (X,Y),23.04545,1.00909,1.57080
line (X,Y),23.05455,2.49091
arc2 (X,Y),23.06364,2.49091,-1.57080
arc2 (X,Y),23.06364,2.49091,-1.57080
line (X,Y),23.07273,1.00909
arc2 (X,Y),23.08182,1.00909,1.57080
arc2 (X,Y),23.08182,1.00909,1.57080
line (X,Y),23.09091,2.49091
arc2 (X,Y),23.10000,2.49091,-1.57080
arc2 (X,Y),23.10000,2.49091,-1.57080
line (X,Y),23.10909,1.00909
arc2 (X,Y),23.11818,1.00909,1.57080
arc2 (X,Y),23.11818,1.00909,1.57080
line (X,Y),23.12727,2.49091
arc2 (X,Y),23.13636,2.49091,-1.57080
arc2 (X,Y),23.13636,2.49091,-1.57080
line (X,Y),23.14545,1.00909
arc2 (X,Y),23.15454,1.00909,1.57080
arc2 (X,Y),23.15454,1.00909,1.57080
line (X,Y),23.16364,2.49091
arc2 (X,Y),23.17273,2.49091,-1.57080
arc2 (X,Y),23.17273,2.49091,-1.57080
line (X,Y),23.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),21.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),21.51818,3.80000
line (X,Y),21.51818,6.89091
arc2 (X,Y),21.52727,6.89091,-1.57080
arc2 (X,Y),21.52727,6.89091,-1.57080
line (X,Y),21.53636,3.80909
arc2 (X,Y),21.54545,3.80909,1.57080
arc2 (X,Y),21.54545,3.80909,1.57080
line (X,Y),21.55455,6.89091
arc2 (X,Y),21.56364,6.89091,-1.57080
arc2 (X,Y),21.56364,6.89091,-1.57080
line (X,Y),21.57273,3.80909
arc2 (X,Y),21.58182,3.80909,1.57080
arc2 (X,Y),21.58182,3.80909,1.57080
line (X,Y),21.59091,6.89091
arc2 (X,Y),21.60000,6.89091,-1.57080
arc2 (X,Y),21.60000,6.89091,-1.57080
line (X,Y),21.60909,3.80909
arc2 (X,Y),21.61818,3.80909,1.57080
arc2 (X,Y),21.61818,3.80909,1.57080
line (X,Y),21.62727,6.89091
arc2 (X,Y),21.63636,6.89091,-1.57080
arc2 (X,Y),21.63636,6.89091,-1.57080
line (X,Y),21.64545,3.80909
arc2 (X,Y),21.65454,3.80909,1.57080
arc2 (X,Y),21.65454,3.80909,1.57080
line (X,Y),21.66364,6.89091
arc2 (X,Y),21.67273,6.89091,-1.57080
arc2 (X,Y),21.67273,6.89091,-1.57080
line (X,Y),21.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),25.00000,0.50000
line (X,Y),25.00000,0.00000
line (X,Y),25.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),29.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),30.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),28.01818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),28.01818,1.00000
line (X,Y),28.01818,2.49091
arc2 (X,Y),28.02727,2.49091,-1.57080
arc2 (X,Y),28.02727,2.49091,-1.57080
line (X,Y),28.03636,1.00909
arc2 (X,Y),28.04545,1.00909,1.57080
arc2 (X,Y),28.04545,1.00909,1.57080
line (X,Y),28.05455,2.49091
arc2 (X,Y),28.06364,2.49091,-1.57080
arc2 (X,Y),28.06364,2.49091,-1.57080
line (X,Y),28.07273,1.00909
arc2 (X,Y),28.08182,1.00909,1.57080
arc2 (X,Y),28.08182,1.00909,1.57080
line (X,Y),28.09091,2.49091
arc2 (X,Y),28.10000,2.49091,-1.57080
arc2 (X,Y),28.10000,2.49091,-1.57080
line (X,Y),28.10909,1.00909
arc2 (X,Y),28.11818,1.00909,1.57080
arc2 (X,Y),28.11818,1.00909,1.57080
line (X,Y),28.12727,2.49091
arc2 (X,Y),28.13636,2.49091,-1.57080
arc2 (X,Y),28.13636,2.49091,-1.57080
line (X,Y),28.14545,1.00909
arc2 (X,Y),28.15454,1.00909,1.57080
arc2 (X,Y),28.15454,1.00909,1.57080
line (X,Y),28.16364,2.49091
arc2 (X,Y),28.17273,2.49091,-1.57080
arc2 (X,Y),28.17273,2.49091,-1.57080
line (X,Y),28.18182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),26.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),26.51818,3.80000
line (X,Y),26.51818,6.89091
arc2 (X,Y),26.52727,6.89091,-1.57080
arc2 (X,Y),26.52727,6.89091,-1.57080
line (X,Y),26.53636,3.80909
arc2 (X,Y),26.54545,3.80909,1.57080
arc2 (X,Y),26.54545,3.80909,1.57080
line (X,Y),26.55455,6.89091
arc2 (X,Y),26.56364,6.89091,-1.57080
arc2 (X,Y),26.56364,6.89091,-1.57080
line (X,Y),26.57273,3.80909
arc2 (X,Y),26.58182,3.80909,1.57080
arc2 (X,Y),26.58182,3.80909,1.57080
line (X,Y),26.59091,6.89091
arc2 (X,Y),26.60000,6.89091,-1.57080
arc2 (X,Y),26.60000,6.89091,-1.57080
line (X,Y),26.60909,3.80909
arc2 (X,Y),26.61818,3.80909,1.57080
arc2 (X,Y),26.61818,3.80909,1.57080
line (X,Y),26.62727,6.89091
arc2 (X,Y),26.63636,6.89091,-1.57080
arc2 (X,Y),26.63636,6.89091,-1.57080
line (X,Y),26.64545,3.80909
arc2 (X,Y),26.65454,3.80909,1.57080
arc2 (X,Y),26.65454,3.80909,1.57080
line (X,Y),26.66364,6.89091
arc2 (X,Y),26.67273,6.89091,-1.57080
arc2 (X,Y),26.67273,6.89091,-1.57080
line (X,Y),26.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

STOP
