#0
! **********************************
! Generated by: 
! Axes: XYZTR=XYZ
! Resolution: 1 counts per unit
! Source File: C:\Users\User\Desktop\Ji Zhang\Soft Matter paper\AuNafthic4\5-PPtop.dxf
! **********************************

! Make sure to update all Alignment positions before run
! Alignment Structure: 
If (gIntFindFids = 1)
     gDblFidX(1) = 0
     gDblFidY(1) = 0
     gDblFidX(2) = 0
     gDblFidY(2) = 0
     Stop
End

ptp/ev (X,Y),0.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),0.00000,0.50000
line (X,Y),0.00000,0.00000
line (X,Y),0.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),4.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),3.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),3.41818,1.00000
line (X,Y),3.41818,2.49091
arc2 (X,Y),3.42727,2.49091,-1.57080
arc2 (X,Y),3.42727,2.49091,-1.57080
line (X,Y),3.43636,1.00909
arc2 (X,Y),3.44546,1.00909,1.57080
arc2 (X,Y),3.44546,1.00909,1.57080
line (X,Y),3.45455,2.49091
arc2 (X,Y),3.46364,2.49091,-1.57080
arc2 (X,Y),3.46364,2.49091,-1.57080
line (X,Y),3.47273,1.00909
arc2 (X,Y),3.48182,1.00909,1.57080
arc2 (X,Y),3.48182,1.00909,1.57080
line (X,Y),3.49091,2.49091
arc2 (X,Y),3.50000,2.49091,-1.57080
arc2 (X,Y),3.50000,2.49091,-1.57080
line (X,Y),3.50909,1.00909
arc2 (X,Y),3.51818,1.00909,1.57080
arc2 (X,Y),3.51818,1.00909,1.57080
line (X,Y),3.52727,2.49091
arc2 (X,Y),3.53636,2.49091,-1.57080
arc2 (X,Y),3.53636,2.49091,-1.57080
line (X,Y),3.54546,1.00909
arc2 (X,Y),3.55455,1.00909,1.57080
arc2 (X,Y),3.55455,1.00909,1.57080
line (X,Y),3.56364,2.49091
arc2 (X,Y),3.57273,2.49091,-1.57080
arc2 (X,Y),3.57273,2.49091,-1.57080
line (X,Y),3.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),1.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),1.51818,3.80000
line (X,Y),1.51818,6.89091
arc2 (X,Y),1.52727,6.89091,-1.57080
arc2 (X,Y),1.52727,6.89091,-1.57080
line (X,Y),1.53636,3.80909
arc2 (X,Y),1.54546,3.80909,1.57080
arc2 (X,Y),1.54546,3.80909,1.57080
line (X,Y),1.55455,6.89091
arc2 (X,Y),1.56364,6.89091,-1.57080
arc2 (X,Y),1.56364,6.89091,-1.57080
line (X,Y),1.57273,3.80909
arc2 (X,Y),1.58182,3.80909,1.57080
arc2 (X,Y),1.58182,3.80909,1.57080
line (X,Y),1.59091,6.89091
arc2 (X,Y),1.60000,6.89091,-1.57080
arc2 (X,Y),1.60000,6.89091,-1.57080
line (X,Y),1.60909,3.80909
arc2 (X,Y),1.61818,3.80909,1.57080
arc2 (X,Y),1.61818,3.80909,1.57080
line (X,Y),1.62727,6.89091
arc2 (X,Y),1.63636,6.89091,-1.57080
arc2 (X,Y),1.63636,6.89091,-1.57080
line (X,Y),1.64546,3.80909
arc2 (X,Y),1.65455,3.80909,1.57080
arc2 (X,Y),1.65455,3.80909,1.57080
line (X,Y),1.66364,6.89091
arc2 (X,Y),1.67273,6.89091,-1.57080
arc2 (X,Y),1.67273,6.89091,-1.57080
line (X,Y),1.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),0.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),0.00000,0.50000
line (X,Y),0.00000,0.00000
line (X,Y),0.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),5.00000,0.50000
line (X,Y),5.00000,0.00000
line (X,Y),5.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),9.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),8.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),8.41818,1.00000
line (X,Y),8.41818,2.49091
arc2 (X,Y),8.42727,2.49091,-1.57080
arc2 (X,Y),8.42727,2.49091,-1.57080
line (X,Y),8.43636,1.00909
arc2 (X,Y),8.44546,1.00909,1.57080
arc2 (X,Y),8.44546,1.00909,1.57080
line (X,Y),8.45455,2.49091
arc2 (X,Y),8.46364,2.49091,-1.57080
arc2 (X,Y),8.46364,2.49091,-1.57080
line (X,Y),8.47273,1.00909
arc2 (X,Y),8.48182,1.00909,1.57080
arc2 (X,Y),8.48182,1.00909,1.57080
line (X,Y),8.49091,2.49091
arc2 (X,Y),8.50000,2.49091,-1.57080
arc2 (X,Y),8.50000,2.49091,-1.57080
line (X,Y),8.50909,1.00909
arc2 (X,Y),8.51818,1.00909,1.57080
arc2 (X,Y),8.51818,1.00909,1.57080
line (X,Y),8.52727,2.49091
arc2 (X,Y),8.53636,2.49091,-1.57080
arc2 (X,Y),8.53636,2.49091,-1.57080
line (X,Y),8.54546,1.00909
arc2 (X,Y),8.55455,1.00909,1.57080
arc2 (X,Y),8.55455,1.00909,1.57080
line (X,Y),8.56364,2.49091
arc2 (X,Y),8.57273,2.49091,-1.57080
arc2 (X,Y),8.57273,2.49091,-1.57080
line (X,Y),8.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),6.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),6.51818,3.80000
line (X,Y),6.51818,6.89091
arc2 (X,Y),6.52727,6.89091,-1.57080
arc2 (X,Y),6.52727,6.89091,-1.57080
line (X,Y),6.53636,3.80909
arc2 (X,Y),6.54546,3.80909,1.57080
arc2 (X,Y),6.54546,3.80909,1.57080
line (X,Y),6.55455,6.89091
arc2 (X,Y),6.56364,6.89091,-1.57080
arc2 (X,Y),6.56364,6.89091,-1.57080
line (X,Y),6.57273,3.80909
arc2 (X,Y),6.58182,3.80909,1.57080
arc2 (X,Y),6.58182,3.80909,1.57080
line (X,Y),6.59091,6.89091
arc2 (X,Y),6.60000,6.89091,-1.57080
arc2 (X,Y),6.60000,6.89091,-1.57080
line (X,Y),6.60909,3.80909
arc2 (X,Y),6.61818,3.80909,1.57080
arc2 (X,Y),6.61818,3.80909,1.57080
line (X,Y),6.62727,6.89091
arc2 (X,Y),6.63636,6.89091,-1.57080
arc2 (X,Y),6.63636,6.89091,-1.57080
line (X,Y),6.64545,3.80909
arc2 (X,Y),6.65455,3.80909,1.57080
arc2 (X,Y),6.65455,3.80909,1.57080
line (X,Y),6.66364,6.89091
arc2 (X,Y),6.67273,6.89091,-1.57080
arc2 (X,Y),6.67273,6.89091,-1.57080
line (X,Y),6.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),5.00000,0.50000
line (X,Y),5.00000,0.00000
line (X,Y),5.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),10.00000,0.50000
line (X,Y),10.00000,0.00000
line (X,Y),10.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),14.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),13.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),13.41818,1.00000
line (X,Y),13.41818,2.49091
arc2 (X,Y),13.42727,2.49091,-1.57080
arc2 (X,Y),13.42727,2.49091,-1.57080
line (X,Y),13.43636,1.00909
arc2 (X,Y),13.44545,1.00909,1.57080
arc2 (X,Y),13.44545,1.00909,1.57080
line (X,Y),13.45455,2.49091
arc2 (X,Y),13.46364,2.49091,-1.57080
arc2 (X,Y),13.46364,2.49091,-1.57080
line (X,Y),13.47273,1.00909
arc2 (X,Y),13.48182,1.00909,1.57080
arc2 (X,Y),13.48182,1.00909,1.57080
line (X,Y),13.49091,2.49091
arc2 (X,Y),13.50000,2.49091,-1.57080
arc2 (X,Y),13.50000,2.49091,-1.57080
line (X,Y),13.50909,1.00909
arc2 (X,Y),13.51818,1.00909,1.57080
arc2 (X,Y),13.51818,1.00909,1.57080
line (X,Y),13.52727,2.49091
arc2 (X,Y),13.53636,2.49091,-1.57080
arc2 (X,Y),13.53636,2.49091,-1.57080
line (X,Y),13.54545,1.00909
arc2 (X,Y),13.55455,1.00909,1.57080
arc2 (X,Y),13.55455,1.00909,1.57080
line (X,Y),13.56364,2.49091
arc2 (X,Y),13.57273,2.49091,-1.57080
arc2 (X,Y),13.57273,2.49091,-1.57080
line (X,Y),13.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),11.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),11.51818,3.80000
line (X,Y),11.51818,6.89091
arc2 (X,Y),11.52727,6.89091,-1.57080
arc2 (X,Y),11.52727,6.89091,-1.57080
line (X,Y),11.53636,3.80909
arc2 (X,Y),11.54545,3.80909,1.57080
arc2 (X,Y),11.54545,3.80909,1.57080
line (X,Y),11.55455,6.89091
arc2 (X,Y),11.56364,6.89091,-1.57080
arc2 (X,Y),11.56364,6.89091,-1.57080
line (X,Y),11.57273,3.80909
arc2 (X,Y),11.58182,3.80909,1.57080
arc2 (X,Y),11.58182,3.80909,1.57080
line (X,Y),11.59091,6.89091
arc2 (X,Y),11.60000,6.89091,-1.57080
arc2 (X,Y),11.60000,6.89091,-1.57080
line (X,Y),11.60909,3.80909
arc2 (X,Y),11.61818,3.80909,1.57080
arc2 (X,Y),11.61818,3.80909,1.57080
line (X,Y),11.62727,6.89091
arc2 (X,Y),11.63636,6.89091,-1.57080
arc2 (X,Y),11.63636,6.89091,-1.57080
line (X,Y),11.64545,3.80909
arc2 (X,Y),11.65455,3.80909,1.57080
arc2 (X,Y),11.65455,3.80909,1.57080
line (X,Y),11.66364,6.89091
arc2 (X,Y),11.67273,6.89091,-1.57080
arc2 (X,Y),11.67273,6.89091,-1.57080
line (X,Y),11.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),10.00000,0.50000
line (X,Y),10.00000,0.00000
line (X,Y),10.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),15.00000,0.50000
line (X,Y),15.00000,0.00000
line (X,Y),15.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),19.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),18.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),18.41818,1.00000
line (X,Y),18.41818,2.49091
arc2 (X,Y),18.42727,2.49091,-1.57080
arc2 (X,Y),18.42727,2.49091,-1.57080
line (X,Y),18.43636,1.00909
arc2 (X,Y),18.44546,1.00909,1.57080
arc2 (X,Y),18.44546,1.00909,1.57080
line (X,Y),18.45455,2.49091
arc2 (X,Y),18.46364,2.49091,-1.57080
arc2 (X,Y),18.46364,2.49091,-1.57080
line (X,Y),18.47273,1.00909
arc2 (X,Y),18.48182,1.00909,1.57080
arc2 (X,Y),18.48182,1.00909,1.57080
line (X,Y),18.49091,2.49091
arc2 (X,Y),18.50000,2.49091,-1.57080
arc2 (X,Y),18.50000,2.49091,-1.57080
line (X,Y),18.50909,1.00909
arc2 (X,Y),18.51818,1.00909,1.57080
arc2 (X,Y),18.51818,1.00909,1.57080
line (X,Y),18.52727,2.49091
arc2 (X,Y),18.53636,2.49091,-1.57080
arc2 (X,Y),18.53636,2.49091,-1.57080
line (X,Y),18.54545,1.00909
arc2 (X,Y),18.55455,1.00909,1.57080
arc2 (X,Y),18.55455,1.00909,1.57080
line (X,Y),18.56364,2.49091
arc2 (X,Y),18.57273,2.49091,-1.57080
arc2 (X,Y),18.57273,2.49091,-1.57080
line (X,Y),18.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),16.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),16.51818,3.80000
line (X,Y),16.51818,6.89091
arc2 (X,Y),16.52727,6.89091,-1.57080
arc2 (X,Y),16.52727,6.89091,-1.57080
line (X,Y),16.53636,3.80909
arc2 (X,Y),16.54545,3.80909,1.57080
arc2 (X,Y),16.54545,3.80909,1.57080
line (X,Y),16.55455,6.89091
arc2 (X,Y),16.56364,6.89091,-1.57080
arc2 (X,Y),16.56364,6.89091,-1.57080
line (X,Y),16.57273,3.80909
arc2 (X,Y),16.58182,3.80909,1.57080
arc2 (X,Y),16.58182,3.80909,1.57080
line (X,Y),16.59091,6.89091
arc2 (X,Y),16.60000,6.89091,-1.57080
arc2 (X,Y),16.60000,6.89091,-1.57080
line (X,Y),16.60909,3.80909
arc2 (X,Y),16.61818,3.80909,1.57080
arc2 (X,Y),16.61818,3.80909,1.57080
line (X,Y),16.62727,6.89091
arc2 (X,Y),16.63636,6.89091,-1.57080
arc2 (X,Y),16.63636,6.89091,-1.57080
line (X,Y),16.64545,3.80909
arc2 (X,Y),16.65454,3.80909,1.57080
arc2 (X,Y),16.65454,3.80909,1.57080
line (X,Y),16.66364,6.89091
arc2 (X,Y),16.67273,6.89091,-1.57080
arc2 (X,Y),16.67273,6.89091,-1.57080
line (X,Y),16.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),15.00000,0.50000
line (X,Y),15.00000,0.00000
line (X,Y),15.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),20.00000,0.50000
line (X,Y),20.00000,0.00000
line (X,Y),20.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),24.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),23.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),23.41818,1.00000
line (X,Y),23.41818,2.49091
arc2 (X,Y),23.42727,2.49091,-1.57080
arc2 (X,Y),23.42727,2.49091,-1.57080
line (X,Y),23.43636,1.00909
arc2 (X,Y),23.44546,1.00909,1.57080
arc2 (X,Y),23.44546,1.00909,1.57080
line (X,Y),23.45455,2.49091
arc2 (X,Y),23.46364,2.49091,-1.57080
arc2 (X,Y),23.46364,2.49091,-1.57080
line (X,Y),23.47273,1.00909
arc2 (X,Y),23.48182,1.00909,1.57080
arc2 (X,Y),23.48182,1.00909,1.57080
line (X,Y),23.49091,2.49091
arc2 (X,Y),23.50000,2.49091,-1.57080
arc2 (X,Y),23.50000,2.49091,-1.57080
line (X,Y),23.50909,1.00909
arc2 (X,Y),23.51818,1.00909,1.57080
arc2 (X,Y),23.51818,1.00909,1.57080
line (X,Y),23.52727,2.49091
arc2 (X,Y),23.53636,2.49091,-1.57080
arc2 (X,Y),23.53636,2.49091,-1.57080
line (X,Y),23.54545,1.00909
arc2 (X,Y),23.55455,1.00909,1.57080
arc2 (X,Y),23.55455,1.00909,1.57080
line (X,Y),23.56364,2.49091
arc2 (X,Y),23.57273,2.49091,-1.57080
arc2 (X,Y),23.57273,2.49091,-1.57080
line (X,Y),23.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),21.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),21.51818,3.80000
line (X,Y),21.51818,6.89091
arc2 (X,Y),21.52727,6.89091,-1.57080
arc2 (X,Y),21.52727,6.89091,-1.57080
line (X,Y),21.53636,3.80909
arc2 (X,Y),21.54545,3.80909,1.57080
arc2 (X,Y),21.54545,3.80909,1.57080
line (X,Y),21.55455,6.89091
arc2 (X,Y),21.56364,6.89091,-1.57080
arc2 (X,Y),21.56364,6.89091,-1.57080
line (X,Y),21.57273,3.80909
arc2 (X,Y),21.58182,3.80909,1.57080
arc2 (X,Y),21.58182,3.80909,1.57080
line (X,Y),21.59091,6.89091
arc2 (X,Y),21.60000,6.89091,-1.57080
arc2 (X,Y),21.60000,6.89091,-1.57080
line (X,Y),21.60909,3.80909
arc2 (X,Y),21.61818,3.80909,1.57080
arc2 (X,Y),21.61818,3.80909,1.57080
line (X,Y),21.62727,6.89091
arc2 (X,Y),21.63636,6.89091,-1.57080
arc2 (X,Y),21.63636,6.89091,-1.57080
line (X,Y),21.64545,3.80909
arc2 (X,Y),21.65454,3.80909,1.57080
arc2 (X,Y),21.65454,3.80909,1.57080
line (X,Y),21.66364,6.89091
arc2 (X,Y),21.67273,6.89091,-1.57080
arc2 (X,Y),21.67273,6.89091,-1.57080
line (X,Y),21.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),20.00000,0.50000
line (X,Y),20.00000,0.00000
line (X,Y),20.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),25.00000,0.50000
line (X,Y),25.00000,0.00000
line (X,Y),25.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),29.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),30.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),28.41818,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),28.41818,1.00000
line (X,Y),28.41818,2.49091
arc2 (X,Y),28.42727,2.49091,-1.57080
arc2 (X,Y),28.42727,2.49091,-1.57080
line (X,Y),28.43636,1.00909
arc2 (X,Y),28.44546,1.00909,1.57080
arc2 (X,Y),28.44546,1.00909,1.57080
line (X,Y),28.45455,2.49091
arc2 (X,Y),28.46364,2.49091,-1.57080
arc2 (X,Y),28.46364,2.49091,-1.57080
line (X,Y),28.47273,1.00909
arc2 (X,Y),28.48182,1.00909,1.57080
arc2 (X,Y),28.48182,1.00909,1.57080
line (X,Y),28.49091,2.49091
arc2 (X,Y),28.50000,2.49091,-1.57080
arc2 (X,Y),28.50000,2.49091,-1.57080
line (X,Y),28.50909,1.00909
arc2 (X,Y),28.51818,1.00909,1.57080
arc2 (X,Y),28.51818,1.00909,1.57080
line (X,Y),28.52727,2.49091
arc2 (X,Y),28.53636,2.49091,-1.57080
arc2 (X,Y),28.53636,2.49091,-1.57080
line (X,Y),28.54545,1.00909
arc2 (X,Y),28.55455,1.00909,1.57080
arc2 (X,Y),28.55455,1.00909,1.57080
line (X,Y),28.56364,2.49091
arc2 (X,Y),28.57273,2.49091,-1.57080
arc2 (X,Y),28.57273,2.49091,-1.57080
line (X,Y),28.58182,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),26.51818,3.80000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),26.51818,3.80000
line (X,Y),26.51818,6.89091
arc2 (X,Y),26.52727,6.89091,-1.57080
arc2 (X,Y),26.52727,6.89091,-1.57080
line (X,Y),26.53636,3.80909
arc2 (X,Y),26.54545,3.80909,1.57080
arc2 (X,Y),26.54545,3.80909,1.57080
line (X,Y),26.55455,6.89091
arc2 (X,Y),26.56364,6.89091,-1.57080
arc2 (X,Y),26.56364,6.89091,-1.57080
line (X,Y),26.57273,3.80909
arc2 (X,Y),26.58182,3.80909,1.57080
arc2 (X,Y),26.58182,3.80909,1.57080
line (X,Y),26.59091,6.89091
arc2 (X,Y),26.60000,6.89091,-1.57080
arc2 (X,Y),26.60000,6.89091,-1.57080
line (X,Y),26.60909,3.80909
arc2 (X,Y),26.61818,3.80909,1.57080
arc2 (X,Y),26.61818,3.80909,1.57080
line (X,Y),26.62727,6.89091
arc2 (X,Y),26.63636,6.89091,-1.57080
arc2 (X,Y),26.63636,6.89091,-1.57080
line (X,Y),26.64545,3.80909
arc2 (X,Y),26.65454,3.80909,1.57080
arc2 (X,Y),26.65454,3.80909,1.57080
line (X,Y),26.66364,6.89091
arc2 (X,Y),26.67273,6.89091,-1.57080
arc2 (X,Y),26.67273,6.89091,-1.57080
line (X,Y),26.68182,3.80000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),25.00000,0.50000
line (X,Y),25.00000,0.00000
line (X,Y),25.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

STOP
