#0
! **********************************
! Generated by: 
! Axes: XYZTR=XYZ
! Resolution: 1 counts per unit
! Source File: C:\Users\User\Desktop\Ji Zhang\Soft Matter paper\AuPPthic4\7-naftop.dxf
! **********************************

! Make sure to update all Alignment positions before run
! Alignment Structure: 
If (gIntFindFids = 1)
     gDblFidX(1) = 0
     gDblFidY(1) = 0
     gDblFidX(2) = 0
     gDblFidY(2) = 0
     Stop
End

ptp/ev (X,Y),0.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),0.00000,0.50000
line (X,Y),0.00000,0.00000
line (X,Y),0.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),4.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),5.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),1.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),1.43636,3.70000
line (X,Y),1.43636,6.98182
arc2 (X,Y),1.45455,6.98182,-1.57080
arc2 (X,Y),1.45455,6.98182,-1.57080
line (X,Y),1.47273,3.71818
arc2 (X,Y),1.49091,3.71818,1.57080
arc2 (X,Y),1.49091,3.71818,1.57080
line (X,Y),1.50909,6.98182
arc2 (X,Y),1.52727,6.98182,-1.57080
arc2 (X,Y),1.52727,6.98182,-1.57080
line (X,Y),1.54546,3.71818
arc2 (X,Y),1.56364,3.71818,1.57080
arc2 (X,Y),1.56364,3.71818,1.57080
line (X,Y),1.58182,6.98182
arc2 (X,Y),1.60000,6.98182,-1.57080
arc2 (X,Y),1.60000,6.98182,-1.57080
line (X,Y),1.61818,3.71818
arc2 (X,Y),1.63636,3.71818,1.57080
arc2 (X,Y),1.63636,3.71818,1.57080
line (X,Y),1.65455,6.98182
arc2 (X,Y),1.67273,6.98182,-1.57080
arc2 (X,Y),1.67273,6.98182,-1.57080
line (X,Y),1.69091,3.71818
arc2 (X,Y),1.70909,3.71818,1.57080
arc2 (X,Y),1.70909,3.71818,1.57080
line (X,Y),1.72727,6.98182
arc2 (X,Y),1.74546,6.98182,-1.57080
arc2 (X,Y),1.74546,6.98182,-1.57080
line (X,Y),1.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),3.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),3.83636,1.00000
line (X,Y),3.83636,2.48182
arc2 (X,Y),3.85455,2.48182,-1.57080
arc2 (X,Y),3.85455,2.48182,-1.57080
line (X,Y),3.87273,1.01818
arc2 (X,Y),3.89091,1.01818,1.57080
arc2 (X,Y),3.89091,1.01818,1.57080
line (X,Y),3.90909,2.48182
arc2 (X,Y),3.92727,2.48182,-1.57080
arc2 (X,Y),3.92727,2.48182,-1.57080
line (X,Y),3.94546,1.01818
arc2 (X,Y),3.96364,1.01818,1.57080
arc2 (X,Y),3.96364,1.01818,1.57080
line (X,Y),3.98182,2.48182
arc2 (X,Y),4.00000,2.48182,-1.57080
arc2 (X,Y),4.00000,2.48182,-1.57080
line (X,Y),4.01818,1.01818
arc2 (X,Y),4.03636,1.01818,1.57080
arc2 (X,Y),4.03636,1.01818,1.57080
line (X,Y),4.05455,2.48182
arc2 (X,Y),4.07273,2.48182,-1.57080
arc2 (X,Y),4.07273,2.48182,-1.57080
line (X,Y),4.09091,1.01818
arc2 (X,Y),4.10909,1.01818,1.57080
arc2 (X,Y),4.10909,1.01818,1.57080
line (X,Y),4.12727,2.48182
arc2 (X,Y),4.14545,2.48182,-1.57080
arc2 (X,Y),4.14545,2.48182,-1.57080
line (X,Y),4.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),5.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),5.00000,0.50000
line (X,Y),5.00000,0.00000
line (X,Y),5.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),9.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),10.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),6.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),6.43636,3.70000
line (X,Y),6.43636,6.98182
arc2 (X,Y),6.45455,6.98182,-1.57080
arc2 (X,Y),6.45455,6.98182,-1.57080
line (X,Y),6.47273,3.71818
arc2 (X,Y),6.49091,3.71818,1.57080
arc2 (X,Y),6.49091,3.71818,1.57080
line (X,Y),6.50909,6.98182
arc2 (X,Y),6.52727,6.98182,-1.57080
arc2 (X,Y),6.52727,6.98182,-1.57080
line (X,Y),6.54546,3.71818
arc2 (X,Y),6.56364,3.71818,1.57080
arc2 (X,Y),6.56364,3.71818,1.57080
line (X,Y),6.58182,6.98182
arc2 (X,Y),6.60000,6.98182,-1.57080
arc2 (X,Y),6.60000,6.98182,-1.57080
line (X,Y),6.61818,3.71818
arc2 (X,Y),6.63636,3.71818,1.57080
arc2 (X,Y),6.63636,3.71818,1.57080
line (X,Y),6.65455,6.98182
arc2 (X,Y),6.67273,6.98182,-1.57080
arc2 (X,Y),6.67273,6.98182,-1.57080
line (X,Y),6.69091,3.71818
arc2 (X,Y),6.70909,3.71818,1.57080
arc2 (X,Y),6.70909,3.71818,1.57080
line (X,Y),6.72727,6.98182
arc2 (X,Y),6.74546,6.98182,-1.57080
arc2 (X,Y),6.74546,6.98182,-1.57080
line (X,Y),6.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),8.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),8.83636,1.00000
line (X,Y),8.83636,2.48182
arc2 (X,Y),8.85455,2.48182,-1.57080
arc2 (X,Y),8.85455,2.48182,-1.57080
line (X,Y),8.87273,1.01818
arc2 (X,Y),8.89091,1.01818,1.57080
arc2 (X,Y),8.89091,1.01818,1.57080
line (X,Y),8.90909,2.48182
arc2 (X,Y),8.92727,2.48182,-1.57080
arc2 (X,Y),8.92727,2.48182,-1.57080
line (X,Y),8.94546,1.01818
arc2 (X,Y),8.96364,1.01818,1.57080
arc2 (X,Y),8.96364,1.01818,1.57080
line (X,Y),8.98182,2.48182
arc2 (X,Y),9.00000,2.48182,-1.57080
arc2 (X,Y),9.00000,2.48182,-1.57080
line (X,Y),9.01818,1.01818
arc2 (X,Y),9.03636,1.01818,1.57080
arc2 (X,Y),9.03636,1.01818,1.57080
line (X,Y),9.05455,2.48182
arc2 (X,Y),9.07273,2.48182,-1.57080
arc2 (X,Y),9.07273,2.48182,-1.57080
line (X,Y),9.09091,1.01818
arc2 (X,Y),9.10909,1.01818,1.57080
arc2 (X,Y),9.10909,1.01818,1.57080
line (X,Y),9.12727,2.48182
arc2 (X,Y),9.14545,2.48182,-1.57080
arc2 (X,Y),9.14545,2.48182,-1.57080
line (X,Y),9.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),10.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),10.00000,0.50000
line (X,Y),10.00000,0.00000
line (X,Y),10.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),14.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),15.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),11.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),11.43636,3.70000
line (X,Y),11.43636,6.98182
arc2 (X,Y),11.45455,6.98182,-1.57080
arc2 (X,Y),11.45455,6.98182,-1.57080
line (X,Y),11.47273,3.71818
arc2 (X,Y),11.49091,3.71818,1.57080
arc2 (X,Y),11.49091,3.71818,1.57080
line (X,Y),11.50909,6.98182
arc2 (X,Y),11.52727,6.98182,-1.57080
arc2 (X,Y),11.52727,6.98182,-1.57080
line (X,Y),11.54545,3.71818
arc2 (X,Y),11.56364,3.71818,1.57080
arc2 (X,Y),11.56364,3.71818,1.57080
line (X,Y),11.58182,6.98182
arc2 (X,Y),11.60000,6.98182,-1.57080
arc2 (X,Y),11.60000,6.98182,-1.57080
line (X,Y),11.61818,3.71818
arc2 (X,Y),11.63636,3.71818,1.57080
arc2 (X,Y),11.63636,3.71818,1.57080
line (X,Y),11.65455,6.98182
arc2 (X,Y),11.67273,6.98182,-1.57080
arc2 (X,Y),11.67273,6.98182,-1.57080
line (X,Y),11.69091,3.71818
arc2 (X,Y),11.70909,3.71818,1.57080
arc2 (X,Y),11.70909,3.71818,1.57080
line (X,Y),11.72727,6.98182
arc2 (X,Y),11.74545,6.98182,-1.57080
arc2 (X,Y),11.74545,6.98182,-1.57080
line (X,Y),11.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),13.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),13.83636,1.00000
line (X,Y),13.83636,2.48182
arc2 (X,Y),13.85455,2.48182,-1.57080
arc2 (X,Y),13.85455,2.48182,-1.57080
line (X,Y),13.87273,1.01818
arc2 (X,Y),13.89091,1.01818,1.57080
arc2 (X,Y),13.89091,1.01818,1.57080
line (X,Y),13.90909,2.48182
arc2 (X,Y),13.92727,2.48182,-1.57080
arc2 (X,Y),13.92727,2.48182,-1.57080
line (X,Y),13.94545,1.01818
arc2 (X,Y),13.96364,1.01818,1.57080
arc2 (X,Y),13.96364,1.01818,1.57080
line (X,Y),13.98182,2.48182
arc2 (X,Y),14.00000,2.48182,-1.57080
arc2 (X,Y),14.00000,2.48182,-1.57080
line (X,Y),14.01818,1.01818
arc2 (X,Y),14.03636,1.01818,1.57080
arc2 (X,Y),14.03636,1.01818,1.57080
line (X,Y),14.05455,2.48182
arc2 (X,Y),14.07273,2.48182,-1.57080
arc2 (X,Y),14.07273,2.48182,-1.57080
line (X,Y),14.09091,1.01818
arc2 (X,Y),14.10909,1.01818,1.57080
arc2 (X,Y),14.10909,1.01818,1.57080
line (X,Y),14.12727,2.48182
arc2 (X,Y),14.14545,2.48182,-1.57080
arc2 (X,Y),14.14545,2.48182,-1.57080
line (X,Y),14.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),15.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),15.00000,0.50000
line (X,Y),15.00000,0.00000
line (X,Y),15.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),19.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),20.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),16.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),16.43636,3.70000
line (X,Y),16.43636,6.98182
arc2 (X,Y),16.45455,6.98182,-1.57080
arc2 (X,Y),16.45455,6.98182,-1.57080
line (X,Y),16.47273,3.71818
arc2 (X,Y),16.49091,3.71818,1.57080
arc2 (X,Y),16.49091,3.71818,1.57080
line (X,Y),16.50909,6.98182
arc2 (X,Y),16.52727,6.98182,-1.57080
arc2 (X,Y),16.52727,6.98182,-1.57080
line (X,Y),16.54545,3.71818
arc2 (X,Y),16.56364,3.71818,1.57080
arc2 (X,Y),16.56364,3.71818,1.57080
line (X,Y),16.58182,6.98182
arc2 (X,Y),16.60000,6.98182,-1.57080
arc2 (X,Y),16.60000,6.98182,-1.57080
line (X,Y),16.61818,3.71818
arc2 (X,Y),16.63636,3.71818,1.57080
arc2 (X,Y),16.63636,3.71818,1.57080
line (X,Y),16.65454,6.98182
arc2 (X,Y),16.67273,6.98182,-1.57080
arc2 (X,Y),16.67273,6.98182,-1.57080
line (X,Y),16.69091,3.71818
arc2 (X,Y),16.70909,3.71818,1.57080
arc2 (X,Y),16.70909,3.71818,1.57080
line (X,Y),16.72727,6.98182
arc2 (X,Y),16.74545,6.98182,-1.57080
arc2 (X,Y),16.74545,6.98182,-1.57080
line (X,Y),16.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),18.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),18.83636,1.00000
line (X,Y),18.83636,2.48182
arc2 (X,Y),18.85455,2.48182,-1.57080
arc2 (X,Y),18.85455,2.48182,-1.57080
line (X,Y),18.87273,1.01818
arc2 (X,Y),18.89091,1.01818,1.57080
arc2 (X,Y),18.89091,1.01818,1.57080
line (X,Y),18.90909,2.48182
arc2 (X,Y),18.92727,2.48182,-1.57080
arc2 (X,Y),18.92727,2.48182,-1.57080
line (X,Y),18.94546,1.01818
arc2 (X,Y),18.96364,1.01818,1.57080
arc2 (X,Y),18.96364,1.01818,1.57080
line (X,Y),18.98182,2.48182
arc2 (X,Y),19.00000,2.48182,-1.57080
arc2 (X,Y),19.00000,2.48182,-1.57080
line (X,Y),19.01818,1.01818
arc2 (X,Y),19.03636,1.01818,1.57080
arc2 (X,Y),19.03636,1.01818,1.57080
line (X,Y),19.05455,2.48182
arc2 (X,Y),19.07273,2.48182,-1.57080
arc2 (X,Y),19.07273,2.48182,-1.57080
line (X,Y),19.09091,1.01818
arc2 (X,Y),19.10909,1.01818,1.57080
arc2 (X,Y),19.10909,1.01818,1.57080
line (X,Y),19.12727,2.48182
arc2 (X,Y),19.14545,2.48182,-1.57080
arc2 (X,Y),19.14545,2.48182,-1.57080
line (X,Y),19.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),20.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),20.00000,0.50000
line (X,Y),20.00000,0.00000
line (X,Y),20.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),24.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),25.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),21.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),21.43636,3.70000
line (X,Y),21.43636,6.98182
arc2 (X,Y),21.45455,6.98182,-1.57080
arc2 (X,Y),21.45455,6.98182,-1.57080
line (X,Y),21.47273,3.71818
arc2 (X,Y),21.49091,3.71818,1.57080
arc2 (X,Y),21.49091,3.71818,1.57080
line (X,Y),21.50909,6.98182
arc2 (X,Y),21.52727,6.98182,-1.57080
arc2 (X,Y),21.52727,6.98182,-1.57080
line (X,Y),21.54545,3.71818
arc2 (X,Y),21.56364,3.71818,1.57080
arc2 (X,Y),21.56364,3.71818,1.57080
line (X,Y),21.58182,6.98182
arc2 (X,Y),21.60000,6.98182,-1.57080
arc2 (X,Y),21.60000,6.98182,-1.57080
line (X,Y),21.61818,3.71818
arc2 (X,Y),21.63636,3.71818,1.57080
arc2 (X,Y),21.63636,3.71818,1.57080
line (X,Y),21.65454,6.98182
arc2 (X,Y),21.67273,6.98182,-1.57080
arc2 (X,Y),21.67273,6.98182,-1.57080
line (X,Y),21.69091,3.71818
arc2 (X,Y),21.70909,3.71818,1.57080
arc2 (X,Y),21.70909,3.71818,1.57080
line (X,Y),21.72727,6.98182
arc2 (X,Y),21.74545,6.98182,-1.57080
arc2 (X,Y),21.74545,6.98182,-1.57080
line (X,Y),21.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),23.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),23.83636,1.00000
line (X,Y),23.83636,2.48182
arc2 (X,Y),23.85455,2.48182,-1.57080
arc2 (X,Y),23.85455,2.48182,-1.57080
line (X,Y),23.87273,1.01818
arc2 (X,Y),23.89091,1.01818,1.57080
arc2 (X,Y),23.89091,1.01818,1.57080
line (X,Y),23.90909,2.48182
arc2 (X,Y),23.92727,2.48182,-1.57080
arc2 (X,Y),23.92727,2.48182,-1.57080
line (X,Y),23.94545,1.01818
arc2 (X,Y),23.96364,1.01818,1.57080
arc2 (X,Y),23.96364,1.01818,1.57080
line (X,Y),23.98182,2.48182
arc2 (X,Y),24.00000,2.48182,-1.57080
arc2 (X,Y),24.00000,2.48182,-1.57080
line (X,Y),24.01818,1.01818
arc2 (X,Y),24.03636,1.01818,1.57080
arc2 (X,Y),24.03636,1.01818,1.57080
line (X,Y),24.05455,2.48182
arc2 (X,Y),24.07273,2.48182,-1.57080
arc2 (X,Y),24.07273,2.48182,-1.57080
line (X,Y),24.09091,1.01818
arc2 (X,Y),24.10909,1.01818,1.57080
arc2 (X,Y),24.10909,1.01818,1.57080
line (X,Y),24.12727,2.48182
arc2 (X,Y),24.14545,2.48182,-1.57080
arc2 (X,Y),24.14545,2.48182,-1.57080
line (X,Y),24.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),25.00000,0.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),25.00000,0.50000
line (X,Y),25.00000,0.00000
line (X,Y),25.50000,0.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),29.50000,8.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.50000,8.00000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),30.00000,7.50000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
ptp/e (X,Y),30.00000,8.50000
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),26.43636,3.70000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),26.43636,3.70000
line (X,Y),26.43636,6.98182
arc2 (X,Y),26.45455,6.98182,-1.57080
arc2 (X,Y),26.45455,6.98182,-1.57080
line (X,Y),26.47273,3.71818
arc2 (X,Y),26.49091,3.71818,1.57080
arc2 (X,Y),26.49091,3.71818,1.57080
line (X,Y),26.50909,6.98182
arc2 (X,Y),26.52727,6.98182,-1.57080
arc2 (X,Y),26.52727,6.98182,-1.57080
line (X,Y),26.54545,3.71818
arc2 (X,Y),26.56364,3.71818,1.57080
arc2 (X,Y),26.56364,3.71818,1.57080
line (X,Y),26.58182,6.98182
arc2 (X,Y),26.60000,6.98182,-1.57080
arc2 (X,Y),26.60000,6.98182,-1.57080
line (X,Y),26.61818,3.71818
arc2 (X,Y),26.63636,3.71818,1.57080
arc2 (X,Y),26.63636,3.71818,1.57080
line (X,Y),26.65454,6.98182
arc2 (X,Y),26.67273,6.98182,-1.57080
arc2 (X,Y),26.67273,6.98182,-1.57080
line (X,Y),26.69091,3.71818
arc2 (X,Y),26.70909,3.71818,1.57080
arc2 (X,Y),26.70909,3.71818,1.57080
line (X,Y),26.72727,6.98182
arc2 (X,Y),26.74545,6.98182,-1.57080
arc2 (X,Y),26.74545,6.98182,-1.57080
line (X,Y),26.76364,3.70000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

ptp/ev (X,Y),28.83636,1.00000,gDblRapidSpeed
Start gIntSubBuffer,ShutterOpen;TILL PST(gIntSubBuffer).#RUN = 0
wait 2
MSEG (X,Y),28.83636,1.00000
line (X,Y),28.83636,2.48182
arc2 (X,Y),28.85455,2.48182,-1.57080
arc2 (X,Y),28.85455,2.48182,-1.57080
line (X,Y),28.87273,1.01818
arc2 (X,Y),28.89091,1.01818,1.57080
arc2 (X,Y),28.89091,1.01818,1.57080
line (X,Y),28.90909,2.48182
arc2 (X,Y),28.92727,2.48182,-1.57080
arc2 (X,Y),28.92727,2.48182,-1.57080
line (X,Y),28.94545,1.01818
arc2 (X,Y),28.96364,1.01818,1.57080
arc2 (X,Y),28.96364,1.01818,1.57080
line (X,Y),28.98182,2.48182
arc2 (X,Y),29.00000,2.48182,-1.57080
arc2 (X,Y),29.00000,2.48182,-1.57080
line (X,Y),29.01818,1.01818
arc2 (X,Y),29.03636,1.01818,1.57080
arc2 (X,Y),29.03636,1.01818,1.57080
line (X,Y),29.05455,2.48182
arc2 (X,Y),29.07273,2.48182,-1.57080
arc2 (X,Y),29.07273,2.48182,-1.57080
line (X,Y),29.09091,1.01818
arc2 (X,Y),29.10909,1.01818,1.57080
arc2 (X,Y),29.10909,1.01818,1.57080
line (X,Y),29.12727,2.48182
arc2 (X,Y),29.14545,2.48182,-1.57080
arc2 (X,Y),29.14545,2.48182,-1.57080
line (X,Y),29.16364,1.00000
ENDS (X,Y)
till (^X_AST.#MOVE) & (^Y_AST.#MOVE)
Start gIntSubBuffer,ShutterClose;TILL PST(gIntSubBuffer).#RUN = 0
wait 2

STOP
